const AUTO_REFRESH_INTERVAL_TIME = 30000; //30 seconds
const DOWNLOAD_INTERVAL_TIME = 30000; //30 seconds
const DOWNLOAD_LIMIT = 5;
const TIME_AMOUNT = 7;
const TIME_UNIT = "day";

export { AUTO_REFRESH_INTERVAL_TIME, DOWNLOAD_INTERVAL_TIME, DOWNLOAD_LIMIT, TIME_AMOUNT, TIME_UNIT };
